Feature/#25
wooda-ege/lovebird-backend pull request #34
Opened 2023-06-26 16:18 UTC by skmwit

> ### PR Introduce  
Calendar 도메인 추가

> ### Description  
미래의 데이트 일정을 공유할 수 있는 캘린더 기능 개발  

> ### Core Features  
Calendar CRUD  
Calendar 엔터티 추가  

```java
@Builder
    public Calendar(Long memberId, String title, String memo, LocalDateTime startDate, LocalDateTime endDate){
        this.memberId=memberId;
        this.title=title;
        this.memo=memo;
        this.startDate=startDate;
        this.endDate=endDate;
        auditEntity=new AuditEntity();
    }
```  
Controller 개발  

```java
@RestController
@RequiredArgsConstructor
@RequestMapping("/api/v1/calendar")
public class CalendarController {
    private final CalendarService calendarService;
    private final MemberService memberService;

    @PostMapping("")
    public ResponseEntity<ApiResponse<Long>> save(
            @Validated @RequestPart(value = "calendarCreateRequest")CalendarCreateRequest calendar
            ) throws IOException {
        Long id = calendarService.save(calendar);
        return new ResponseEntity<>(
                ApiResponse.createSuccessWithData(CalendarResponseMessage.CREATE_CALENDAR.getMessage(), id),
                HttpStatus.CREATED
        );
    }

    @GetMapping("")
    public ResponseEntity<ApiResponse<List<Calendar>>> getCalendar(@RequestParam Long memberId){
        List<Calendar> calendarList=calendarService.findByMemberId(memberId);
        return ResponseEntity.ok(
                ApiResponse.createSuccessWithData(CalendarResponseMessage.READ_CALENDAR.getMessage(),
                        calendarList)
        );
    }

    @PutMapping("/{id}")
    public ResponseEntity<ApiResponse<Long>> update(
            @PathVariable Long id,
            @Validated @RequestPart(value = "calendarUpdateRequest") CalendarUpdateRequest calendarUpdateRequest
    ) throws IOException{
        Long updatedId=calendarService.update(id, calendarUpdateRequest);
        return ResponseEntity.ok(
          ApiResponse.createSuccessWithData(CalendarResponseMessage.UPDATE_CALENDAR.getMessage(), updatedId)
        );
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<ApiResponse<?>> delete(@PathVariable Long id){
        return ResponseEntity.ok(ApiResponse.createSuccess(CalendarResponseMessage.DELETE_CALENDAR.getMessage()));
    }
}
```

> ### etc  
테스트 코드 작성 미완료  
엔터티 수정 필요시 코멘트 달아주세요~

2023-06-26 23:38 UTC, lcomment requested changes
리뷰 남겼습니다~~

2023-06-26 23:38 UTC, lcomment commented on src/main/java/com/ege/wooda/domain/calendar/dto/response/CalendarDetailResponse.java
> +}
빼먹은거 같네..?

2023-06-26 23:38 UTC, lcomment commented on src/main/java/com/ege/wooda/domain/calendar/repository/CalendarRepository.java
> +    List<Calendar> findByMemberId(Long id);
Jpa가 알아서 쿼리를 생성해주고 있어서 규칙에 맞게 메서드만 작성하면 JPQL을 활용 안해도 될듯??

2023-06-26 23:38 UTC, lcomment commented on src/main/java/com/ege/wooda/domain/calendar/dto/request/CalendarUpdateRequest.java
> +public record CalendarUpdateRequest(Long memberId,
memberId도 필수값으로 넘겨줘야 할거 같아

2023-06-26 23:38 UTC, lcomment commented on src/main/java/com/ege/wooda/domain/calendar/dto/request/CalendarCreateRequest.java
> +    }
이 메서드는 안사용하고 있어서 지워도 될듯??

2023-06-26 23:38 UTC, lcomment commented on src/main/java/com/ege/wooda/domain/calendar/controller/CalendarController.java
> +@RequestMapping("/api/v1/calendar")
나는 구현할 때 전체적으로 `/api/v1/{id}/**`로 매핑해서 memberId를 필수로 받아줬는데, Path로 받는거랑 dto에 넣는거 중 하나로 통일해야 할거 같네

2023-06-26 23:38 UTC, lcomment commented on src/main/java/com/ege/wooda/domain/calendar/controller/CalendarController.java
> +    public ResponseEntity<ApiResponse<List<Calendar>>> getCalendar(@RequestParam Long memberId){
밑에 CalenderDetailResponse 구현하고 제네릭 바꿔줘!

2023-06-26 23:38 UTC, lcomment commented on src/main/java/com/ege/wooda/domain/calendar/controller/CalendarController.java
> +    private final MemberService memberService;
난 각 API 메서드에 아래 어노테이션을 사용했어

```java
@PreAuthorize("#id == authentication.principal.id")
```

클라이언트로부터 요청과 함께 받은 id와 인증 받은 유저 id가 일치하는지 확인해주는 어노테이션이야. 나는 이 부분에서 일단 Member 조회를 해준다고 생각해서 따로 MemberService를 주입 받지 않았는데 뭐가 맞는지는 모르겠네 ㅋㅋㅋ 만약 저 어노테이션이 내가 생각한대로 동작하면 서비스를 주입 받는 반복적인 코드는 생략할 수 있지 않을까..?

@doorBW 어떻게 생각하십니까??

2023-07-02 09:24 UTC, skmwit commented
@lcomment 수정할 수 있는 부분은 수정했고 merge 충돌난 부분도 해결해놨습니다 
확인하시고 머지 해주세요~~

2023-07-03 01:29 UTC, lcomment reviewed
리뷰 남겼어요~

2023-07-03 01:29 UTC, lcomment commented on src/main/java/com/ege/wooda/domain/calendar/domain/Calendar.java
> +        }};
요 부분은 까먹고 안 지운건가??

2023-07-03 01:30 UTC, lcomment approved these changes

2023-07-05 14:10 UTC, merged